//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AiS.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AiS.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DECLARE @transaction varchar(50) = &apos;UpdateStructureTransaction&apos;;
        ///DECLARE @errorCode int;
        ///DECLARE @version varchar(30) = &apos;1.0.0.0&apos;;
        ///
        ///BEGIN TRANSACTION @transaction;
        ///
        ///SET ANSI_NULLS ON ;
        ///SET QUOTED_IDENTIFIER ON ;
        ///SET ANSI_PADDING ON;
        /// 
        ///IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N&apos;[dbo].[Versions]&apos;) AND type in (N&apos;U&apos;)) 
        ///BEGIN
        ///CREATE TABLE [dbo].[Versions](
        ///	[ID] [int] IDENTITY(1,1) NOT NULL,
        ///	[UpdateDate] [datetime] NOT NULL,
        ///	[Version] [nvarchar](20) NOT NULL
        ///) ON [P [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQL_1_0_0_0 {
            get {
                return ResourceManager.GetString("SQL_1_0_0_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE [Versions] (
        ///  [ID] int IDENTITY (1,1) NOT NULL
        ///, [UpdateDate] datetime NOT NULL
        ///, [Version] nvarchar(20) NOT NULL
        ///);
        ///
        ///CREATE TABLE [Teachers] (
        ///  [ID] nvarchar(10) NOT NULL
        ///, [Title] nvarchar(50) NOT NULL
        ///, [Name] nvarchar(100) NOT NULL
        ///, [Lastname] nvarchar(150) NOT NULL
        ///, [TitleSuffix] nvarchar(50) NOT NULL
        ///);
        ///
        ///CREATE TABLE [SubjectTeachers] (
        ///  [TeacherID] nvarchar(10) NOT NULL
        ///, [SubjectID] nvarchar(10) NOT NULL
        ///);
        ///
        ///CREATE TABLE [Subjects] (
        ///  [ID] nvarchar(10) NOT NULL [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SQLCE_1_0_0_0 {
            get {
                return ResourceManager.GetString("SQLCE_1_0_0_0", resourceCulture);
            }
        }
    }
}
